### ISSUE TITLE
Typings issues when upgrading to 1.4.0-rc1

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/reactxp#804]
I'm trying to migrate from ^1.3.0-rc.6 to 1.4.0-rc1 and I'm hitting a bunch of tsc errors with the ref object.

I installed 1.4.0-rc1 in the RXP example app and didn't hit the same issues until I set ["strict": true](https://www.typescriptlang.org/docs/handbook/compiler-options.html) in [tsconfig](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/tsconfig.json).
1.3.0-rc6 didn't have any problems with strict=true, but it looks like 1.4.0-rc1 does.

Specifically, I suspect that the ```strictFunctionTypes``` flag is the one that is causing problems.

```
C:\code\reactxp\samples\hello-world>npm run rn-watch

ssrc/App.tsx:36:17 - error TS2326: Types of property 'ref' are incompatible.
  Type '(navigator: NavigatorImpl) => void' is not assignable to type 'string | (string & ((obj: Component<any, any, any>) => void)) | (string & RefObject<Component<any...'.
    Type '(navigator: NavigatorImpl) => void' is not assignable to type '((instance: NavigatorImpl) => any) & RefObject<Component<any, any, any>>'.
      Type '(navigator: NavigatorImpl) => void' is not assignable to type 'RefObject<Component<any, any, any>>'.
        Property 'current' is missing in type '(navigator: NavigatorImpl) => void'.

36                 ref={ this._onNavigatorRef }
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/SecondPanel.tsx:113:29 - error TS2326: Types of property 'ref' are incompatible.
  Type '(component: Video) => void' is not assignable to type 'string | (string & ((obj: Component<any, any, any>) => void)) | (string & RefObject<Component<any...'.
    Type '(component: Video) => void' is not assignable to type '((instance: Video) => any) & RefObject<Component<any, any, any>>'.
      Type '(component: Video) => void' is not assignable to type 'RefObject<Component<any, any, any>>'.
        Property 'current' is missing in type '(component: Video) => void'.

113                             ref={ this._onMountVideo }
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by luisnaranjo733** [comment]
New info: I manually upgraded to each intermediary release between 1.3.0-rc.6 and 1.4.0-rc.1.

I was able to upgrade to each and tsc would compile.
It only breaks when moving from 1.3.3 to 1.4.0-rc.1.

1.3.3 was released on 8/3, and 1.4.0-rc.1 was released on 9/9, some commit between then is causing the regression.

**Comment by luisnaranjo733** [comment]
Could this commit be related?

https://github.com/Microsoft/reactxp/commit/ebe1aaeab588a444eb00ecf9c6210f5994d368d2

**Comment by luisnaranjo733** [comment]
Or this one 

https://github.com/Microsoft/reactxp/commit/7a9b8b816eb73694a480f617564d9778f5cdddc6

**Comment by erictraut** [comment]
What type is _onMountVideo and _onMountVideo in the example above? 

I introduced a regression in commit [ebe1aae](https://github.com/Microsoft/reactxp/commit/ebe1aaeab588a444eb00ecf9c6210f5994d368d2) and attempted to fix it in commit [7a9b8b8](https://github.com/Microsoft/reactxp/commit/7a9b8b816eb73694a480f617564d9778f5cdddc6).

The problem is that earlier versions of @types/react don't include the definition of RefObject, so ReactXP no longer worked with these older versions. I tried to work around this by adding a local version of RefObject. It should match the type definition in @types/react. I wonder if that type definition has changed. If that's the underlying cause, a workaround is to export the local version of RefObject from RX so you can use RX.Types.RefObject within your app code. That would guarantee that the types would match even if @types/react changes again in the future.

**Comment by luisnaranjo733** [comment]
[_onMountVideo](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/src/SecondPanel.tsx#L125) is from the hello-world app that is checked in to the ReactXP source.

I don't think the root issue is that the @types/react type changed. I made sure the exact type that ReactXP is expecting was installed on the client app. I suspect the issue is that this fix in commit 7a9b8b8 doesn't pass tsc when the "strictFunctionTypes": "true" flag is turned on in tsconfig. This is one of the flags that gets turned on when "strict": "true" in tsconfig.

It that is the issue - should the XP test app should use "strict": "true" to catch tsc errors like this in the future?

**Comment by erictraut** [comment]
Yeah, enabling this compiling mode is a good idea. The TodoList sample was already using “strict”. I’ve enabled it for the other samples as well and fixed up the resulting compiler errors.
